[project]
name = "recursor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kosong[contrib]>=0.36.1",
    "rich>=14.2.0",
]
